# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "db") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

sqlite_default: &sqlite_default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "vecstore_development") %>
  cache:
    <<: *sqlite_default
    database: storage/development_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *sqlite_default
    database: storage/development_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *sqlite_default
    database: storage/development_cable.sqlite3
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: vecstore_test

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "vecstore_production") %>
  cache:
    <<: *sqlite_default
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *sqlite_default
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *sqlite_default
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate

